apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  type: ClusterIP
  ports:
    - port: 15672
      targetPort: 15672
      protocol: TCP
      name: http
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: amqp